# SPDX-FileCopyrightText: 2020 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/linux-qt6-static.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/json-validation.yml

