# SPDX-FileCopyrightText: 2023-2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: gcompris
confinement: strict
grade: stable
base: core24
adopt-info: gcompris
apps:
  gcompris:
    extensions:
      - kde-neon-6
    common-id: org.kde.gcompris.desktop
    desktop: usr/share/applications/org.kde.gcompris.desktop
    command: usr/bin/gcompris-qt
    plugs:
      - home
      - pulseaudio
      - audio-playback
      - alsa
plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404
environment:
  ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
  QT_MEDIA_BACKEND: "ffmpeg"
  XDG_CACHE_HOME: "$SNAP_USER_DATA/.local/usr/share"
layout:
  "/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib":
    symlink: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib"
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.gcompris
    bus: session
parts:
  qml-box2d:
    source: https://github.com/qml-box2d/qml-box2d.git
    plugin: cmake
    build-packages:
      - cmake
      - libpulse0
    stage-packages:
      - webp
      - libpulse0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DBUILD_STANDALONE=ON
  gcompris:
    after:
      - qml-box2d
    parse-info:
      - usr/share/metainfo/org.kde.gcompris.appdata.xml
    plugin: cmake
    build-packages:
      - cmake
      - libssl-dev
      - gettext
    stage-packages:
      - libasound2
      - libasound2-data
      - libasound2-plugins
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  cleanup:
    after:
      - gcompris
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

